# ================================================
# Core Settings
# ================================================

title: "Portfolio de Donald Job"
subtitle: "Data Scientist | Machine Learning Engineer"
name: "Donald Job"
url: "https://DonaldJobDev.github.io"
baseurl: ""
repository: "DonaldJobDev/DonaldJobDev.github.io"
locale: "fr-FR"  # Langue française
timezone: "Europe/Paris"

# ================================================
# Theme Configuration
# ================================================

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"  # Thème sombre moderne
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# ================================================
# Content Collections
# ================================================

collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/

defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      read_time: false
      share: true
      related: false

# ================================================
# Navigation
# ================================================

navigation:
  main:
    - title: "Accueil"
      url: /
    - title: "Projets"
      url: /portfolio/
    - title: "À Propos"
      url: /about/

# ================================================
# Author Profile
# ================================================

author:
  name: "Donald Job"
  avatar: "/assets/images/profile.jpg"  # Ajouter votre photo (400x400px)
  bio: "Data Scientist spécialisé en Machine Learning et analyse prédictive"
  location: "Paris, France"
  email: "contact@donaldjob.dev"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/DonaldJobDev"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/donaldjob"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:contact@donaldjob.dev"

# ================================================
# Footer Configuration
# ================================================

footer:
  links:
    - label: "Mentions légales"
      url: /legal/
    - label: "Confidentialité"
      url: /privacy/

# ================================================
# Advanced Settings
# ================================================

# Désactiver les fonctionnalités inutiles
breadcrumbs: false
comments:
  provider: false
search: true

# Optimisation SEO
google_site_verification: "votre_clé_google"
twitter:
  username: "@DonaldJobDev"

# Performance
sass:
  style: compressed
compress_html:
  clippings: all
  ignore:
    envs: development

# Exclusions
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - node_modules
  - package.json
  - package-lock.json
